### PR TITLE
[Feature] Server test runner

### LINKED ISSUE #4: Add a test runner to the server
We need a test runner and a better server structure that supports testing as much as possible.

### PR DESCRIPTION
**Pull request by drgmr**
Refactored how the GraphQL schema is built, added [Jest](https://facebook.github.io/jest/) as a test runner for the server side and added an example test file that checks for the output of one of the field resolvers. Test utilities can be added as the application grows (database mocking, end-to-end test utilities, etc).

Closes #4

### CODE REVIEW

**Comment by anibalsolon** [comment]
Awesome @edupc !

Took some time to me to figure out the fields, but now I got it: it is to load specializes fields, such as the user object from a center, instead of just getting the ID.

Do you know if it will be possible to test our queries? Or the query handlers.

**Comment by anibalsolon** [comment]
About the testing, got this: `/opt/app/src/schema/center/fields.test.js:18:3: 'expect' is not defined.`
Is it missing the `chai` lib?

**Comment by drgmr** [comment]
@anibalsolon about query testing, I still need to look into what is the best way to mock whatever is necessary to get full coverage, but I don't see anything that can get in the way.

The `expect` error was actually a linting error - I had the wrong env set on the test file, it should be OK now.

**Comment by anibalsolon** [comment]
Great, tested here and worked flawlessly. Well formatted output from Jest :ok_hand: 

PR is ok for me!

**Pull request merged**
